#ifndef SRC_ENGINE_CONSTANTS_H_
#define SRC_ENGINE_CONSTANTS_H_

/*
 * Copyright 2020 Maui Kelley
 */

#define NUM_VERTEX_TOKENS 5
#define NUM_FACE_TOKENS 4
#define NUM_TEXTURE_VERTEX_TOKENS 3
#define W_DEFAULT 1.0f
#define VERTEX_SIZE 4
#define TEXTURE_VERTEX_SIZE 2
#define FACE_SIZE 3
#define NORMAL_SIZE 3
#define COLOR_SIZE 4
#define GLUBYTE_SHIFT 8
#define EOS '\0'
#define PI 3.14159265f
#define MIN_FRUSTUM_ANGLE 1
#define MAX_FRUSTUM_ANGEL 179
#define MAX_LIGHTS 8
#define NUM_DIFFUSE_PARAMS 4
#define DIFFUSE_ALPHA 3
#define AMBIENT_SIZE 4
#define DIFFUSE_SIZE 4
#define SPECULAR_SIZE 4
#define EMISSION_SIZE 4
#define SPECULAR_EXPONENT_MULTIPLIER 128.0f/1000.0f
#define COLOR_MAX 255

#endif  // SRC_ENGINE_CONSTANTS_H_
