#ifndef SRC_ENGINE_CONSTANTS_H_
#define SRC_ENGINE_CONSTANTS_H_

/*
 * Copyright 2020 Maui Kelley
 */

#define NUM_VERTEX_TOKENS 5
#define NUM_FACE_TOKENS 4
#define NUM_TEXTURE_VERTEX_TOKENS 3
#define W_DEFAULT 1.0f
#define VERTEX_SIZE 4
#define TEXTURE_VERTEX_SIZE 2
#define FACE_SIZE 3
#define NORMAL_SIZE 3
#define COLOR_SIZE 4
#define GLUBYTE_SHIFT 8
#define EOS '\0'
#define PI 3.14159265f
#define MIN_FRUSTUM_ANGLE 1
#define MAX_FRUSTUM_ANGEL 179
#define MAX_LIGHTS 8
#define NUM_DIFFUSE_PARAMS 4
#define DIFFUSE_ALPHA 3
#define AMBIENT_SIZE 4
#define DIFFUSE_SIZE 4
#define SPECULAR_SIZE 4
#define EMISSION_SIZE 4
#define SPECULAR_EXPONENT_MULTIPLIER 128.0f/1000.0f
#define RGB_MAX 255
#define RGB_SIZE 3
#define NUM_PPM_ATTRIBUTES 3
#define NUM_BOX_POINTS 8
#define NUM_BOX_AXIS 6
#define WINDOW_WIDTH 1920
#define WINDOW_HEIGHT 1080
#define ENGINE_CURSOR_X 0
#define ENGINE_CURSOR_Y 1
#define ENGINE_DEAD_ZONE 0.2f
#define ENGINE_MOUSE_SENSITIVITY 10
#define UI_MAX_WIDTH 100
#define UI_MAX_HEIGHT 100
#define UI_NUM_VERTICES 4
#define UI_NUM_FACES 4

enum input_types {ENGINE_GAMEPAD, ENGINE_KEYBOARD, ENGINE_MOUSE, ENGINE_AXIS,
                  ENGINE_CURSOR};
enum ui_positions {UI_LEFT_TOP, UI_CENTER_TOP, UI_RIGHT_TOP,
               UI_LEFT_CENTER, UI_CENTER_CENTER, UI_RIGHT_CENTER,
               UI_LEFT_BOTTOM, UI_CENTER_BOTTOM, UI_RIGHT_BOTTOM};
enum ui_fixed {UI_NOT_FIX, UI_FIX_WIDTH, UI_FIX_HEIGHT};
enum animation_actions {ANIMATION_STOP, ANIMATION_REPEAT, ANIMATION_TRANSITION};
#endif  // SRC_ENGINE_CONSTANTS_H_
